<%@ CodeTemplate Language="C#" TargetLanguage="Text" Description="This template demonstrates using template script blocks." %>
<%-- 
This template demonstrates using template script blocks.
--%>

<%@ Property Name="SourceTable" Type="System.String" Default="SourceTable" Description="The table to use for this sample." %>

<%@ Property Name="lstString" Type="System.Collections.Generic.List<string>" Description="The table to use for this sample." %>

// This class generated by CodeSmith on <%= DateTime.Now.ToLongDateString() %>

"This is some static content (just like the static HTML in a ASP page)."
<%-- 
This template demonstrates using template script blocks.
--%>
<%= "This is dynamic content using an expression  %> write construct." %>

<%= SomeStringMethod() %>

<% SomeRenderMethod(); %>

<%= SourceTable%>

This is more static content.

<script runat="template">

Response.Write("This is 'more dynamic c\'ontent usi'ng a render method.");

string SomeStringMethod()
{
	return "Today's date: " + DateTime.Now.ToString("MM/dd/yyyy");
}

void SomeRenderMethod()
{
	Response.Write("This is 'more dynamic c\'ontent usi'ng a render method.");
	Response.Write("Hello " + System.Environment.UserName + "!");
}
</script>

<script >
function SomeStringMethod()
{
	alert("MM/dd/yyyy");
}

</script>

<%= SomeStringMethod() %>

<% SomeRenderMethod(); %>

<%  int count = 10; %>

<%  

string a = "safasdfasd";

if (count != 10) 
{
%>
now the count is 10
<%  
}else {
%>
now the count is <%=a%>;
<%  
}
%>



<%  for (int i=0;i< count ;i++) 
{
%>
output line <%=i%>
<%  
}
%>

<%  foreach (string s in lstString) 
{
%>
output line <%=s%>
<%  
}
%>